### PR TITLE
Fix getSketch

### LINKED ISSUE #959: Fix getSketch
It seems that when we were making changes to the request structure, getSketch was neglected. It should be changed to return a promise, and its usages in ViewOnly.js should also be changed to reflect that change

### PR DESCRIPTION
**Pull request by MDZHX**
Fixes #959.

### CODE REVIEW

File: src/components/ViewOnly.js [hunk 1]
```diff
@@ -1,10 +1,12 @@
+/* eslint-disable react/destructuring-assignment */
```
Comment (lumisphere902) [inline src/components/ViewOnly.js:1]: We talked about it already, but generally you shouldn't disable eslint rules without a good reason.

File: src/components/ViewOnly.js [hunk 2]
```diff
@@ -74,21 +86,27 @@ class ViewOnly extends React.Component {
...
-      this.setState({ notfound: true });
-      return;
+  codeSaverHelper = () => {
+    try {
+      fetch
+        .getSketch(this.props.mostRecentProgram)
+        .then((res) => {
+          if (!res.ok) {
+            this.setState({ notfound: true });
+            return;
```
Comment (lumisphere902) [inline src/components/ViewOnly.js:98]: Same promise changes as above

**Review by lumisphere902 — CHANGES_REQUESTED** [review]
Most of the refactor looks good, there are just a couple of errors with how promises are handled. Good job!

File: src/components/ViewOnly.js [hunk 3]
```diff
@@ -32,115 +35,164 @@ class ViewOnly extends React.Component {
...
     if (this.savePrevProgram) {
       await this.codeSaverHelper();
     }
 
-    const { ok, sketch } = await fetch.getSketch(this.props.programid);
-
-    if (!ok) {
-      this.setState({ notfound: true });
-      return;
+    try {
```
Comment (lumisphere902) [inline src/components/ViewOnly.js:51]: I'm not 100% sure, but I think all cases of bad things happening will be caught by the `.catch` function on the promise, so you don't need a separate try/catch system

File: src/components/ViewOnly.js [hunk 4]
```diff
@@ -32,115 +35,164 @@ class ViewOnly extends React.Component {
...
-    );
+  }
 
-    if (!okOriginal) {
-      this.setState({ notfound: true });
-      return;
+  codeSaverHelper = () => {
+    const { mostRecentProgram } = this.props;
+
+    try {
```
Comment (lumisphere902) [inline src/components/ViewOnly.js:107]: Same here

File: src/components/ViewOnly.js [hunk 5]
```diff
@@ -32,115 +35,164 @@ class ViewOnly extends React.Component {
...
+          theme={theme}
           onThemeChange={this.onThemeChange}
         />
         <div className="editor" style={codeStyle}>
           <EditorAndOutput
             // view mode
-            viewMode={this.state.viewMode}
-            updateViewMode={(viewMode) => this.setState({ viewMode })}
+            viewMode={viewMode}
+            updateViewMode={(_viewMode) => this.setState({ viewMode: _viewMode })}
```
Comment (lumisphere902) [inline src/components/ViewOnly.js:176]: nit: this could be named something else like `vm`, as the underscore usually implies the variable is unused

**Review by lumisphere902 — CHANGES_REQUESTED** [review]
Hey Zihan, this looks way better; the promise handling is really clean now. There are still a couple of minor topics, but other than that this is almost good to merge!

**Review by lumisphere902 — APPROVED** [review]
LGTM! Good job on this Pr
