### PR TITLE
fix: refactor error component

### LINKED ISSUE #727: Refactor Error.js into a functional component
https://github.com/uclaacm/TeachLAFrontend/blob/master/src/components/Error.js

### PR DESCRIPTION
**Pull request by LucasGabrielBecker**
This PR intends to refactor the Error component to a functional component.
Closes #727

### CODE REVIEW

File: src/components/Error.js [hunk 1]
```diff
@@ -3,41 +3,40 @@ import React from 'react';
...
-        <div className="page-container">
-          <h2>Uh oh, something went wrong!</h2>
-          <h1>
-            Error:
-            {this.props.errorMsg}
-          </h1>
-          <br />
-          <Button color="primary" size="lg" target="_blank" href={`${GH_REPO_NAME}/issues`}>
-            Let Us Know!
+const Error = function ({ errorMsg, returnTo = null, isValidUser }) {
```
Comment (lumisphere902) [inline src/components/Error.js:11]:
```suggestion
function Error ({ errorMsg, returnTo = null, isValidUser }) {
```

**Review by lumisphere902 — COMMENTED** [review]
LGTM, just a small change to address the lint warning

**Review by lumisphere902 — APPROVED** [review]
